<p>Mapserver provides OGC web-services that can be used to <strong>pull soil data directly from ISRIC servers
</strong> (Please check <a href="https://isric.org/about/data-policy" target="_blank">ISRIC's data policy,
 disclaimer and citation</a>).</p>
<br><p>GIS softwares like <a href="https://qgis.org" target="_blank">QGIS</a> 
 and ArcGIS can be used to download data for specific areas, together with links bellow indicated.</p>
<br> For 
 data citation and license, please consult our: <a href="https://www.isric.org/about/data-policy" target="_blank">
 Data and Software Policy</a><br><br><p><strong>Please check the ISRIC tutorial on how to access layers: </strong>
 </p>
<p><strong>WMS: </strong><a href="https://www.isric.org/instruction-wms" target="_blank">
 https://www.isric.org/instruction-wms</a></p>
<p><strong>WCS: </strong><a href="https://www.isric.org/web-coverage-services-wcs" target="_blank">
 https://www.isric.org/web-coverage-services-wcs</a></p>
<br><p><strong>For soilgrids FAQ and information: 
 </strong><a href="https://www.isric.org/explore/soilgrids/faq-soilgrids" target="_blank">Soilgrids FAQ</a>
 </p>
